### PR TITLE
Add PnET-Succession and Output Biomass PnET to the UCLv2 image

### PR DESCRIPTION
**Pull request by achubaty**
Adds **PnET-Succession** and **Output Biomass PnET** to the `landis-ii-v8-uclv2-release` image, now that upstream has published UCL v2 updates for the PnET stack (see #43).

The `landis-ii-v8-release` (UCLv1) image is unaffected — PnET is already in it, and the `UCL_update` branches are UCLv2-only.

## What's ready upstream

| Repo | Commit | Notes |
| --- | --- | --- |
| Extension-PnET-Succession | [`de21116`](https://github.com/LANDIS-II-Foundation/Extension-PnET-Succession/commit/de21116b9abfa3d7d3740bb99c2cf7a001cce89d) (`UCL_update`) | .csproj retargeted to UniversalCohorts-v2 / InitialCommunity.Universal-v2 / Succession-v10; **no `.cs` changes** vs 6.0.3 |
| Extension-Output-Biomass-PnET | [`e97cdfa`](https://github.com/LANDIS-II-Foundation/Extension-Output-Biomass-PnET/commit/e97cdfaeef60cec9b5c429554647bfa9354d6e25) (`UCL_update`) | same retargeting |
| Library-PnET-Cohort | [`3c40197`](https://github.com/LANDIS-II-Foundation/Library-PnET-Cohort/commit/3c40197848b7b66c31882ce87d82037e42820737) (`UCL_update`) | v2.2, built against the v2 libs; holds the actual code changes |

None are merged to their default branch yet — each is 1 commit behind, and that commit is docs/release-notes only. The yaml entries note to switch to `master` SHAs once upstream merges.

## The one thing the branches don't provide

`Support-Library-Dlls-v8` still ships `Landis.Library.PnETCohorts-v2.dll` **v2.1.1**, built against `UniversalCohorts-v1` and untouched since 2025-05-02. Compiling either PnET extension against it fails the same way Land Use Plus did in #60:

```
error CS0012: The type 'SiteCohorts' is defined in an assembly that is not referenced.
You must add a reference to assembly 'Landis.Library.UniversalCohorts-v1, Version=1.2.0.0, ...'
```

So `libraries-v8-UCL2-prebuild.yaml` rebuilds that library from its `UCL_update` branch **before** the extensions are compiled. The existing library pass runs *after* the extensions, which is only sufficient when an extension needs the rebuilt `.dll` at run time, not to compile against. This file can be dropped once Support-Library-Dlls-v8 ships a UCLv2 build of the library.

## Bug found by the new test: Magic Harvest was broken in the published UCLv2 image

The new PnET test is the first UCLv2 test to run Magic Harvest, and it fails immediately:

```
[A]Landis.Library.HarvestManagement.ManagementAreaDataset cannot be cast to
[B]Landis.Library.HarvestManagement.ManagementAreaDataset.
Type A originates from 'Landis.Library.HarvestManagement-v5' ...
Type B originates from 'Landis.Library.HarvestManagement-v4' ...
```

Our hand-maintained `extension_files/Magic Harvest.csproj` references BiomassHarvest-v6 / HarvestManagement-v4 / SiteHarvest-v2, but Biomass Harvest at the UCLv2 pin builds as **v7** against **v5**/**v3**. It compiles fine and only fails at run time — so it shipped unnoticed. Upstream's own `.csproj` at the pinned commit is already v7/v5/v3; ours was the stale part. Fixed with a `Magic Harvest-UCLv2.csproj` variant selected via the `csproj:` field, the same mechanism as Forest Roads in #59.

## Other changes

- `scripts/update_csproj_hintpaths.sh` — compute the path to `build/extensions` per `.csproj` via `realpath`, as `update_csproj_outputpaths.sh` already does. The old `Library-*` heuristic hardcoded `..\build\extensions`, wrong for a library whose `.csproj` lives in `src/` (Library-PnET-Cohort). Latent until now: the only other `src/`-level library `.csproj` (Library-Metadata) has no `HintPath`s.
- `scripts/install_libraries_v8.sh` — fail fast on a failed library build; the pipe to `tee` was masking dotnet's exit code, same fix applied to `install_extensions_v8.sh` in #60. Matters more now that extensions compile against a pre-built library.
- `tests/TestPnET_AllExtension/scenario_UCLv2.txt` — the UCLv2 variant of the PnET gate, sitting beside the `scenario.txt` the v8 image uses and sharing its inputs, with the five extensions this image doesn't ship (Linear Wind, Climate BDA, Land Use Plus, Local Habitat Output, Wildlife Habitat Output) commented out.
- `tests/TestNECN_UCLv2_AllExtension/` folded back into `tests/TestNECN_AllExtension/scenario_UCLv2.txt` the same way — it was a full copy of a 22 MB input tree differing only in `scenario.txt`, so the inputs can no longer drift between the two scenarios. `TestBiomassSuccession_UCLv2_v8` keeps its own directory: its inputs are genuinely vintage-matched to the pinned commit, not a copy. (The `output/forestRoadsSimulation/.gitkeep` that only the UCLv2 copy carried is kept rather than deleted, but note it isn't actually required — Forest Roads creates the directory itself, verified by running the scenario without it.)
- `tests/TestNECN_AllExtension/scenario_UCLv2.txt` — broadened to the extensions the image actually ships: Dynamic Fuel System (added in #58), Magic Harvest with its Biomass Harvest pairing (usable as of the `.csproj` fix above), and Output Biomass-by-Age. The entries still commented out now say why.
- `tests/TestNECN_AllExtension/scenario.txt` — enabled Output-PnET under NECN Succession, which cannot work: that extension reads PnET site variables and NREs in `Output.PnET.ISiteVar.GetIsiteVar` without PnET-Succession. Reproduced in the published `landis-ii-v8-release:main` image; runs to completion with it off. No image build runs this scenario, which is why it went unnoticed.
- UCLv2 README: the "not included" note and extension tables were stale (still listed Dynamic Fuels/Fire, Forest Roads and Magic Harvest as missing).

## Testing

All built locally on this branch:

| Image | Result |
| --- | --- |
| `v8-uclv2` (Ubuntu 24.04) | ✅ builds; 20 extensions registered (was 18); new PnET gate passes alongside the broadened NECN gate, ForCS and Biomass Succession |
| `v8-release` (Ubuntu 24.04) | ✅ builds; `TestPnET_AllExtension` + ForCS + Biomass Succession gates pass — no regression from the shared-script change |
| `v7-release` (Ubuntu 22.04) | ✅ builds; 33 extensions, image contents unchanged |

Also verified beyond the build gate:

- the UCLv2 PnET scenario runs to completion in the **slim runtime image** (not just the build stage), producing the full PnET output set;
- `Landis.Library.PnETCohorts-v2.dll` in the built image references `UniversalCohorts-v2` / `InitialCommunity.Universal-v2`, i.e. the rebuilt UCLv2 library rather than the stale 2.1.1.

## Note for reviewers

@Klemet could you take a look? Two things worth your eye specifically: the Magic Harvest `.csproj` variant (your extension, and the UCLv1 file stays the default for the v8 image), and whether the extensions I left commented out of the new test scenario match what you expect from the UCLv2 image.

One upstream inconsistency I filed separately: the PnET registration files still declare `Version "6.0.3"` while the assemblies build as 6.1, so `Landis.Extensions list` reports 6.0.3 in the image even though the run log prints "Initializing PnET-Succession version 6.1.0.0".

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by Klemet** [comment]
Will take a look at this Monday, thanks Alex !

**Comment by Klemet** [comment]
After taking a look,

- The .csproj variant for Magic Harvest looks good !
- The list of uncommented extensions also looks good to me !
